- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
    - id: isort  # sort imports

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black  # format code 

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8  # check style and code bugs

- repo: https://github.com/PyCQA/pylint
  rev: v2.15.0
  hooks:
    - id: pylint  # analyse code and style

### pre-commit.log